application/models.py
from .app import db
from datetime import datetime
import re

post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '<Tag id: {}, name: {}>'.format(self.id, self.name)


def slugify(title):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', title)

application/posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

application/app.py
from flask import Flask
from application.config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

application/main.py
from application.app import app
from application import view
from application.posts.blueprint import posts

if __name__ == '__main__':
    app.run(debug=True)

app.register_blueprint(posts, url_prefix='/blog')

application/posts/blueprint.py
from flask import request, Blueprint, render_template, redirect, url_for

from application.app import db
from application.posts.forms import PostForm
from ..models import Post, Tag

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except Exception as ex:
            print(ex)

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/')
def index():
    q = request.args.get('q', '')
    page = request.args.get('page', 1, type=int)

    if q:
        post_list = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        post_list = Post.query.order_by(Post.created.desc())

    pages = post_list.paginate(page=page, per_page=4)
    return render_template('posts/index.html', pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first()
    post_list = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, post_list=post_list)

application/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block content_title %}
    New Post
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.create') }}" method="post">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='col-form-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}

            <button type="submit" class="btn btn-success">Create</button>
        </form>
    </div>
{% endblock %}

application/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content_title %}
    Post page
{% endblock %}

{% block content %}

    {% for post in pages.items %}
        <p><a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a></p>
    {% endfor %}

    <nav>
        <ul class="pagination">
            <li {% if not pages.has_prev %} class="page-item disabled" {% endif %}>
                <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            {% for page in pages.iter_pages() %}
                <li {% if page == pages.page %} class="page-item active" {% endif %}>
                    <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
                </li>
            {% endfor %}

            <li {% if not pages.has_next %} class="page-item disabled" {% endif %}>
                <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>

{% endblock %}

application/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content_title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="tag">
        {% for tag in tags %}
            <a class="badge badge-primary" href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                {{ tag.name }}
            </a>
        {% endfor %}
    </div>

    <div class="main-content">
        {{ post.body }}
    </div>
{% endblock %}

application/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block content_title %}
    Post for {{ tag.name }} tag:
{% endblock %}

{% block content %}
    <div class="post">
    {% for post in post_list %}
        <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
    {% endfor %}
    </div>
{% endblock %}

application/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('hello_world') }}">Flask</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('posts.index') }}">Blog <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('posts.create') }}">+ New Post</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q"
                   value="{{ request.args.get('q', '') }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<div class="container">
    <div class="row">
        <h1>
            {% block content_title %}

            {% endblock %}
        </h1>


    </div>
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

application/templates/index.html
{% extends 'base.html' %}

{% block content_title %}
Main page
{% endblock %}

{% block content %}
Some text
{% endblock %}